### ISSUE TITLE
    _, tokens, dimensions, _ = glove_file.split('.') ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by monajalal** [manasRK/glove-gensim#9]
When I change your code to read the twitter glove 200 dimension, I get the following error for Anaconda Python 3. How can I fix that?
```
glove_file="glove.twitter.27B.200d.txt"
_, tokens, dimensions, _ = glove_file.split('.')
```
Error is:

```
(base) tw-mbp-mjalal:glove mjalal$ python test.py 
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    _, tokens, dimensions, _ = glove_file.split('.')
ValueError: too many values to unpack (expected 4)
```

**Comment by nabinkhadka** [comment]
@monajalal Remove the `twitter` part in the filename. So your filename should be `glove.27B.200d.txt` instead of `glove.twitter.27B.200d.txt`

**Comment by swamineha** [comment]
I am getting the following error:

  File "C:\Users\NEHA\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\NEHA\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/NEHA/.spyder-py3/glove sim.py", line 83, in <module>
    prepend_slow(glove_file,gensim_file,gensim_first_line)

  File "C:/Users/NEHA/.spyder-py3/glove sim.py", line 30, in prepend_slow
    for line in fin:

  File "C:\Users\NEHA\Anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 962: character maps to <undefined>
